### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Sycor4x** [MarcCoru/elects#1]
Hi, I came across the paper "End-to-end Learning for Early Classification of Time Series" and it seems like a very useful, general method with applications in many different domains. But I don't see a license document anywhere on this Gthub. Would it be possible for you to add a license? I don't want to run afoul of any license-related problems.

Thanks! Again, I really enjoyed reading the paper.

**Comment by MarcCoru** [comment]
Thanks for the interest. I added a LICENSE file containing the open MIT license.
